/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.Bank.telas;

/**
 *
 * @author USER
 */
import java.sql.*;
import br.com.Bank.dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class TelaTodosUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTodosUsuarios
     */
    Connection conexao = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
     
    public TelaTodosUsuarios() {
        initComponents();
        conexao = ModuloConexao.conector();   
    }
    
    //inicio do metodo para mostrar todos os usuarios
    private void todosRegistros(){   
        String sql = "select  conta.cpf as id ,titular as nome, numConta as NC, saldo, emprestimo from conta inner join usuarios on usuarios.cpf=conta.cpf";
        
        try {
            pst=conexao.prepareStatement(sql); 
            rs = pst.executeQuery();
            tabelaTodosRegistros.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e); 
        }
        
        
    }
    //fim do metodo para gerar todos os registros
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerarRegistros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTodosRegistros = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Todos os Cadastros");
        setPreferredSize(new java.awt.Dimension(364, 350));

        btnGerarRegistros.setText("Gerar Registros");
        btnGerarRegistros.setToolTipText("");
        btnGerarRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRegistrosActionPerformed(evt);
            }
        });

        tabelaTodosRegistros.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tabelaTodosRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaTodosRegistros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnGerarRegistros)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGerarRegistros)
                .addGap(23, 23, 23))
        );

        setBounds(0, 0, 364, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRegistrosActionPerformed
        // TODO add your handling code here:
        todosRegistros();
    }//GEN-LAST:event_btnGerarRegistrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTodosRegistros;
    // End of variables declaration//GEN-END:variables
}
