/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.Bank.telas;
 
/**
 *
 * @author USER
 */
import java.sql.*;
import br.com.Bank.dal.ModuloConexao;
import javax.swing.JOptionPane;
public class TelaEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    Connection conexao = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    public TelaEmprestimo() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    //inicio metodo de emprestimo
    private void confirmaEmprestimo(){   
        
        //verificando se todos os campos foram preenchidos
        //se nao 
        if((textoNovoEmprestimoCpf.getText().isEmpty()) || (textoNovoEmprestimoConta.getText().isEmpty()) || (textoNovoEmprestimoValor.getText().isEmpty())){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos");
        }
        else{//se forem   
             int confirma = JOptionPane.showConfirmDialog(null,"Confirma Operacao?","Atencao", JOptionPane.YES_NO_OPTION);
            
             if(confirma==JOptionPane.YES_OPTION){
                String sql = "update conta set saldo=saldo+?, emprestimo='sim' where cpf=? and numConta=?";
                try {  
                    pst=conexao.prepareStatement(sql);  
                    pst.setString(1, textoNovoEmprestimoValor.getText());
                    pst.setString(2, textoNovoEmprestimoCpf.getText());
                    pst.setString(3, textoNovoEmprestimoConta.getText());
                    int ok=pst.executeUpdate();  
                    
                    if(ok>0){ 
                        JOptionPane.showMessageDialog(null,"Emprestimo realizado");
                        textoNovoEmprestimoValor.setText(null);
                        textoNovoEmprestimoCpf.setText(null);
                        textoNovoEmprestimoConta.setText(null);
                    }
                 
                } catch (Exception e) {
                 
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }
    }
    
    //fim do metodo de emprestimo
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNovoEmprestimoCpf = new javax.swing.JTextField();
        textoNovoEmprestimoConta = new javax.swing.JTextField();
        textoNovoEmprestimoValor = new javax.swing.JTextField();
        btnNovoEmprestimoConfirma = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Novo Emprestimo");
        setPreferredSize(new java.awt.Dimension(362, 362));

        jLabel1.setText("Beneficiario");

        jLabel2.setText("*CPF");

        jLabel3.setText("*Conta");

        jLabel4.setText("*Valor R$:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("*Campos Obrigatorios");

        textoNovoEmprestimoValor.setToolTipText("");

        btnNovoEmprestimoConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Bank/icones/create.png"))); // NOI18N
        btnNovoEmprestimoConfirma.setToolTipText("Confirma");
        btnNovoEmprestimoConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoEmprestimoConfirma.setPreferredSize(new java.awt.Dimension(66, 66));
        btnNovoEmprestimoConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEmprestimoConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoNovoEmprestimoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(textoNovoEmprestimoConta)
                                    .addComponent(textoNovoEmprestimoValor))))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovoEmprestimoConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(textoNovoEmprestimoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoNovoEmprestimoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoNovoEmprestimoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnNovoEmprestimoConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        setBounds(0, 0, 362, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoEmprestimoConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEmprestimoConfirmaActionPerformed
        // TODO add your handling code here:
        confirmaEmprestimo();
    }//GEN-LAST:event_btnNovoEmprestimoConfirmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoEmprestimoConfirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textoNovoEmprestimoConta;
    private javax.swing.JTextField textoNovoEmprestimoCpf;
    private javax.swing.JTextField textoNovoEmprestimoValor;
    // End of variables declaration//GEN-END:variables
}
