/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Bank.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenCad = new javax.swing.JMenu();
        MenCadConta = new javax.swing.JMenuItem();
        MenCadConsulta = new javax.swing.JMenuItem();
        MenCadEmprestimo = new javax.swing.JMenuItem();
        MenCadUsuarios = new javax.swing.JMenuItem();
        MenOperacao = new javax.swing.JMenu();
        MenOperacaoSaldo = new javax.swing.JMenuItem();
        MenOperacaoDeposito = new javax.swing.JMenuItem();
        MenOperacaoExtrato = new javax.swing.JMenuItem();
        MenSobre = new javax.swing.JMenu();
        MenSair = new javax.swing.JMenu();
        MenSairEncerrar = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Desktop.setPreferredSize(new java.awt.Dimension(364, 364));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblData.setText("Data");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Bank/icones/pig.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        MenCad.setText("Cadastro");
        MenCad.setEnabled(false);

        MenCadConta.setText("Nova Conta");
        MenCadConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadContaActionPerformed(evt);
            }
        });
        MenCad.add(MenCadConta);

        MenCadConsulta.setText("Consulta ");
        MenCad.add(MenCadConsulta);

        MenCadEmprestimo.setText("Emprestimo");
        MenCadEmprestimo.setEnabled(false);
        MenCad.add(MenCadEmprestimo);

        MenCadUsuarios.setText("Usuarios");
        MenCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadUsuariosActionPerformed(evt);
            }
        });
        MenCad.add(MenCadUsuarios);

        Menu.add(MenCad);

        MenOperacao.setText("Operacao");

        MenOperacaoSaldo.setText("Saldo");
        MenOperacaoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOperacaoSaldoActionPerformed(evt);
            }
        });
        MenOperacao.add(MenOperacaoSaldo);

        MenOperacaoDeposito.setText("Deposito");
        MenOperacao.add(MenOperacaoDeposito);

        MenOperacaoExtrato.setText("Extrato");
        MenOperacao.add(MenOperacaoExtrato);

        Menu.add(MenOperacao);

        MenSobre.setText("Sobre");
        Menu.add(MenSobre);

        MenSair.setText("Sair");
        MenSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSairActionPerformed(evt);
            }
        });

        MenSairEncerrar.setText("Encerrar Sessao");
        MenSairEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSairEncerrarActionPerformed(evt);
            }
        });
        MenSair.add(MenSairEncerrar);

        Menu.add(MenSair);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblData))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblUsuario)
                .addGap(55, 55, 55)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(675, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenOperacaoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOperacaoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenOperacaoSaldoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void MenSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Quer realmente sair ?","Atencao",JOptionPane.YES_NO_OPTION);
        
        if(sair == JOptionPane.YES_OPTION){
             System.exit(0);
        }  
    }//GEN-LAST:event_MenSairActionPerformed

    private void MenSairEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSairEncerrarActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Quer realmente sair ?","Atencao",JOptionPane.YES_NO_OPTION);
        
        if(sair == JOptionPane.YES_OPTION){
             System.exit(0);
        }
    }//GEN-LAST:event_MenSairEncerrarActionPerformed

    private void MenCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadUsuariosActionPerformed
        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario); 
    }//GEN-LAST:event_MenCadUsuariosActionPerformed

    private void MenCadContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadContaActionPerformed
        // TODO add your handling code here:
        TelaConta conta = new TelaConta();
        conta.setVisible(true);
        Desktop.add(conta);
    }//GEN-LAST:event_MenCadContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    public static javax.swing.JMenu MenCad;
    private javax.swing.JMenuItem MenCadConsulta;
    private javax.swing.JMenuItem MenCadConta;
    public static javax.swing.JMenuItem MenCadEmprestimo;
    private javax.swing.JMenuItem MenCadUsuarios;
    private javax.swing.JMenu MenOperacao;
    private javax.swing.JMenuItem MenOperacaoDeposito;
    private javax.swing.JMenuItem MenOperacaoExtrato;
    private javax.swing.JMenuItem MenOperacaoSaldo;
    private javax.swing.JMenu MenSair;
    private javax.swing.JMenuItem MenSairEncerrar;
    private javax.swing.JMenu MenSobre;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
