/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.Bank.telas;

/**
 *
 * @author USER
 */
import java.sql.*;
import br.com.Bank.dal.ModuloConexao;
import javax.swing.JOptionPane;
public class TelaSaldo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSaldo
     */
    Connection conexao = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    public TelaSaldo() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    private void cliConsulta(){
        
        if((textoCliConsultaSaldoCpf.getText().isEmpty()) || (textoCliConsultaSaldoSenha.getText().isEmpty())){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos");
        }
        else{
            String sql = "select *from conta cross join usuarios on usuarios.cpf=conta.cpf where usuarios.senha=? and usuarios.cpf=?";
            try {
                 
                pst=conexao.prepareStatement(sql);
                pst.setString(1, textoCliConsultaSaldoSenha.getText());
                pst.setString(2, textoCliConsultaSaldoCpf.getText());
                rs=pst.executeQuery();
                
                if(rs.next()){
                    textoCliConsultaSaldo.setText(rs.getString(4));
                }
                else{
                    JOptionPane.showMessageDialog(null,"Dados nao encontrados");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
        }
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoCliConsultaSaldoCpf = new javax.swing.JTextField();
        textoCliConsultaSaldoSenha = new javax.swing.JTextField();
        textoCliConsultaSaldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnConsultaSaldoConfirma = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultar Saldo");
        setPreferredSize(new java.awt.Dimension(362, 350));

        jLabel1.setText("*CPF");

        jLabel2.setText("*Senha");

        jLabel3.setText("Saldo em Conta R$");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("*Campos obrigatorios");

        btnConsultaSaldoConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Bank/icones/seek.png"))); // NOI18N
        btnConsultaSaldoConfirma.setToolTipText("Confirmar");
        btnConsultaSaldoConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaSaldoConfirma.setPreferredSize(new java.awt.Dimension(50, 50));
        btnConsultaSaldoConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaSaldoConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(textoCliConsultaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoCliConsultaSaldoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(textoCliConsultaSaldoSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnConsultaSaldoConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textoCliConsultaSaldoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(textoCliConsultaSaldoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultaSaldoConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoCliConsultaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setBounds(0, 0, 362, 350);
    }// </editor-fold>//GEN-END:initComponents
  
    private void btnConsultaSaldoConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSaldoConfirmaActionPerformed
        // TODO add your handling code here:
        cliConsulta();
    }//GEN-LAST:event_btnConsultaSaldoConfirmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaSaldoConfirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textoCliConsultaSaldo;
    private javax.swing.JTextField textoCliConsultaSaldoCpf;
    private javax.swing.JTextField textoCliConsultaSaldoSenha;
    // End of variables declaration//GEN-END:variables
}
