/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.Bank.telas;

/**
 *
 * @author USER
 */
import java.sql.*;
import br.com.Bank.dal.ModuloConexao;
import javax.swing.JOptionPane;
public class TelaServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaServicos
     */
    Connection conexao = null;
    PreparedStatement pst =null;
    PreparedStatement pst2=null;
    ResultSet rs = null;
     
    public TelaServicos() { 
        initComponents(); 
        conexao = ModuloConexao.conector();
    }
      
    //inicio do metodo Depositar 
    private void confirmaDeposito(){
        String sql = "update conta set saldo=saldo+? where numConta=?";
        String sql2 = "insert into historico(numConta,operacao,valor) values (?,'deposito',?)";
        
        try {
          pst=conexao.prepareStatement(sql);  
          pst2 = conexao.prepareStatement(sql2);
          pst.setString(1, textoServValor.getText());//valor
          pst.setString(2, textoServNumeroConta.getText());//numConta em conta
          pst2.setString(1, textoServNumeroConta.getText());//numConta em historico
          pst2.setString(2, textoServValor.getText());//valor em historico
          int positivo = pst.executeUpdate();
          int positivo2 = pst2.executeUpdate();
          
          if(positivo>0 && positivo2>0){
              JOptionPane.showMessageDialog(null,"Operacao Deposito Realizada som Sucesso");
          }
               
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //fim do metodo depositar
    
    //inicio do metodo sacar
    private void confirmaSaque(){  
        String sql = "select *from conta where numConta=?";
        //String sql2 = "insert into historico(numConta,operacao) values (?,'saque')";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, textoServNumeroConta.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                float saque = Float.parseFloat(textoServValor.getText());
                float emConta = rs.getFloat(4);
                if(emConta<saque){//se o valor do saque for maior que o valor em conta
                    JOptionPane.showMessageDialog(null,"Saldo em Conta Insuficiente");
                    textoServValor.setText(null);
                }   //ate a linha acima tudo ocorreu bem
                else{//caso contrario
                    String sql2 = "update conta set saldo=saldo-? where numConta=?";
                    String sql3 = "insert into historico(numConta,operacao,valor) values (?,'saque',?)";
                        try {  
                            pst=conexao.prepareStatement(sql2);
                            pst2 = conexao.prepareStatement(sql3);
                            pst.setString(1, textoServValor.getText());//valor
                            pst.setString(2, textoServNumeroConta.getText());//numConta em conta
                            pst2.setString(1, textoServNumeroConta.getText());//numConta em historico
                            pst2.setString(2, textoServValor.getText());
                            int yes = pst.executeUpdate();
                            int yes2 = pst2.executeUpdate();  
                            
                            if(yes>0 && yes2>0){
                                JOptionPane.showMessageDialog(null,"Operacao Saque Realizada som Sucesso");
                            }
                                  
                            
                    } catch (Exception e) {
                         JOptionPane.showMessageDialog(null, e);
                    }
                    
                }
            }
     
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }  
    //fim do metodo sacar  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoServNumeroConta = new javax.swing.JTextField();
        textoServValor = new javax.swing.JTextField();
        btnServDepositar = new javax.swing.JButton();
        btnServSacar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Depositos/Saques");
        setPreferredSize(new java.awt.Dimension(364, 350));

        jLabel1.setText("Numero da Conta");

        jLabel2.setText("Valor a Depositar/Sacar em R$");

        textoServNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoServNumeroContaActionPerformed(evt);
            }
        });

        btnServDepositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Bank/icones/create.png"))); // NOI18N
        btnServDepositar.setToolTipText("Depositar");
        btnServDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServDepositar.setPreferredSize(new java.awt.Dimension(65, 65));
        btnServDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServDepositarActionPerformed(evt);
            }
        });

        btnServSacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Bank/icones/delete.png"))); // NOI18N
        btnServSacar.setToolTipText("Sacar");
        btnServSacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServSacar.setPreferredSize(new java.awt.Dimension(65, 65));
        btnServSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServSacarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Depositar");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("Sacar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textoServValor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnServDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(btnServSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoServNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoServNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textoServValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnServDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setBounds(0, 0, 364, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void textoServNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoServNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoServNumeroContaActionPerformed

    private void btnServDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServDepositarActionPerformed
        // TODO add your handling code here:
        confirmaDeposito();
    }//GEN-LAST:event_btnServDepositarActionPerformed

    private void btnServSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServSacarActionPerformed
        // TODO add your handling code here:
        confirmaSaque();
    }//GEN-LAST:event_btnServSacarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServDepositar;
    private javax.swing.JButton btnServSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textoServNumeroConta;
    private javax.swing.JTextField textoServValor;
    // End of variables declaration//GEN-END:variables
}
